### ISSUE TITLE
Dashboard regions set with conditional rendering property to "never".

### ISSUE THREAD

**Issue by toddarave** [OraOpenSource/OMonAPEX#3]
On page 1 (dashboard) the regions are set with the condition to not render them.  When I changed the properties to render them the to 3 regions did not render a graphic.  Other than that issue the application looks great.  Thanks for sharing.

**Comment by iranapex** [comment]
Yes, I know, As I explained on readme file I'm going to fix it on next release (soon) and create those regions as a plugin if possible. Thank you.

**Comment by iranapex** [comment]
Now regions are available on Dashboard (Home) page.
