### ISSUE TITLE
Request use of "Show Maximize Button" property to be set on wide report regions.

### ISSUE THREAD

**Issue by toddarave** [OraOpenSource/OMonAPEX#4]
I'm a fan of the application.  Requesting that the "Show Maximize Button" property be set/checked on report regions that are wide.  That's because the horizontal scroll in the Universal Theme is always at the bottom of the region and not at the bottom of the page/window.  Here's some images that may help show what I mean.  Thanks for the great application.

![image](https://cloud.githubusercontent.com/assets/12352071/13400972/79e5ac66-dec7-11e5-8ef8-7b35bb82eff5.png)

![image](https://cloud.githubusercontent.com/assets/12352071/13400873/099c42c6-dec7-11e5-8da5-c1e187ee50a6.png)

**Comment by iranapex** [comment]
Thank you Todd, Show Maximize Button will add to all reports in next version.

**Comment by iranapex** [comment]
"Show Maximize Button" property on all report regions now available on new version.
